### ISSUE TITLE
Error in class >= "debt" dans core-plot.r

### ISSUE THREAD

**Issue by Jean-Romain** [0ruser/GHGBalance#1]
J’ai fait quelques modifications de la vignette `GHGBalance.Rmd`, mais elle n’est pas encore finie car j’obtiens l’erreur suivante dès que je lance Build > Document :

```
Updating vignettes
Rebuilding GHGBalance.Rmd
Quitting from lines 249-252 (GHGBalance.Rmd) 
Error in class >= "debt" : 
  comparison (5) is possible only for atomic and list types
Calls: suppressPackageStartupMessages ... mutate.tbl_df -> mutate_impl -> <Anonymous> -> eval_tidy
Execution halted
```
Dans le fichier ‘core-plot.r’ (L. 80), j’ai changé `class == "debt` par `class >= "debt"`, mais j’avais la même erreur avant aussi. 

https://github.com/0ruser/GHGBalance/blob/932cb4eb86a5d482871b2b3549f1d3df252773b8/R/core-plot.r#L80

**Comment by 0ruser** [comment]
Je ne pense pas que cet issue soit le probleme de l'erreur lorsque on exécute Build > More > Document. As-tu essayé la nouvelle version du package dans ton local?

**Comment by Jean-Romain** [comment]
Tu avais changé le nom de la colonne `class` par `phase`.
